name: CI (Continuous Integration)
on:
 push:
   branches: [ main ]
 pull_request:
   branches: [ main ]
jobs:
 conviso-sast-cr-sca-ast:
   runs-on: ubuntu-latest
   container:
     image: convisoappsec/flowcli
     env:
       FLOW_API_KEY:  ${{secrets.CONVISO_API_KEY}}
       FLOW_PROJECT_CODE: ${{secrets.PROJECT_KEY}}
       FLOW_API_URL: ${{secrets.HOMOLOGA_URL}}
   steps:
   - uses: actions/checkout@v3
   - name: Run SAST (Static Application Security Testing)
     run: conviso sast run
   - name: Run CR (Code Review)
     run: conviso deploy create with values
   - name: Run SCA (Software Composition Analysis)
     run: conviso sca run
   - name: Run AST (Application Security Testing)
     run: conviso ast run
